name: acceptance-tests-fast
on:
  workflow_run:
    workflows: [Suggested tests to cover this Pull Request]
    types: [completed]
  schedule:
    - cron: '0 */12 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  acceptance-tests-fast:
    uses: "./.github/workflows/acceptance_tests_common.yml"
    with:
      secondary_tests: "18_run_secondary_tests.sh"
      server_id: "secondary"
      recommended_tests: 'recommended-tests.xml'

