name: test_filter

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  filter-paths:
    runs-on: ubuntu-latest
    outputs:
#      require_acceptance_tests: ${{ steps.filter.outputs.java == 'true' || steps.filter.outputs.web == 'true' || steps.filter.outputs.testsuite == 'true' }}
      require_acceptance_tests: ${{ 0 == 1 }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 #v3.0.2
        id: filter
        with:
          filters: |
            java:
              - 'java/**'
            web:
              - 'web/html/src/**'
            testsuite:
              - 'testsuite/**'
              - '!testsuite/features/build_validation/**'
  tests:
    name: Run
    runs-on: ubuntu-24.04
    needs: filter-paths
    steps:
      - name: Yes
        if: ${{ needs.filter-paths.outputs.require_acceptance_tests == 'true' }}
        run: echo Yes
      - name: No
        if: ${{ needs.filter-paths.outputs.require_acceptance_tests == 'false' }}
        run: echo No

